version: "3"
services:
  web:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html
      - ./login.html:/usr/share/nginx/html/login.html
      - ./home.html:/usr/share/nginx/html/home.html
      - ./shop.html:/usr/share/nginx/html/shop.html
      - ./product-detail.html:/usr/share/nginx/html/product-detail.html
      - ./cart.html:/usr/share/nginx/html/cart.html
      - ./about-us.html:/usr/share/nginx/html/about-us.html
      - ./billians.html:/usr/share/nginx/html/billians.html
      - ./script.js:/usr/share/nginx/html/script.js
      - ./styles:/usr/share/nginx/styles
      - ./images:/usr/share/nginx/images
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - my_network

networks:
  my_network:
